FROM ramesesinc/etracs-core:beta

COPY /services /apps/server/services

RUN ln -s /apps/server/services /services
RUN ln -s /apps/server/services/apps/etracs25 /apps/etracs25
RUN ln -s /apps/server/services/apps/notification /apps/notification
