FROM ramesesinc/etracs25-core:255.02

COPY /workspace /apps/server/workspace

RUN ln -s /apps/server/workspace/services /services
RUN ln -s /apps/server/workspace/web /web
RUN ln -s /apps/server/workspace/services/apps/etracs25 /apps/etracs25
